import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Header } from "@/widgets/header";
import { Footer } from "../widgets/footer";
import { ReactQueryClientProvider } from "@/shared/lib/query-client";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full w-full bg-gray-950 text-gray-200`}
      >
        <div className="min-h-screen flex flex-col">
          <ReactQueryClientProvider>
            <Header />
            <main className="grow">{children}</main>
            <Footer />
          </ReactQueryClientProvider>
        </div>
      </body>
    </html>
  );
}
