import type { Metadata } from "next";
import { Comfortaa } from "next/font/google";
import "./globals.css";
import { Header } from "@/widgets/header";
import { Footer } from "../widgets/footer";
import { ReactQueryClientProvider } from "@/shared/lib/query-client";
import ClientProvider from "@/shared/lib/client-provider";

const comfortaa = Comfortaa({ subsets: ["cyrillic", "latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${comfortaa.className}  antialiased h-full w-full bg-gray-950 text-gray-200`}
      >
        <div className="min-h-screen flex flex-col">
          <ReactQueryClientProvider>
            <ClientProvider>
              <Header />
              <main className="grow">{children}</main>
              <Footer />
            </ClientProvider>
          </ReactQueryClientProvider>
        </div>
      </body>
    </html>
  );
}
